'use strict';
const a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
(async()=>{
const base=fs.mkdtempSync(path.join(os.tmpdir(),'ca-protocol-'));let handler,registered=false,ready=false,load;
const done=new Promise((resolve,reject)=>{load={resolve,reject}});
const app={isPackaged:false,getPath:()=>base,setPath(){},on(){},exit(code){load.reject(Error('App exit '+code))},quit(){},requestSingleInstanceLock:()=>true,whenReady(){a(registered);ready=true;return Promise.resolve()}};
const ses={setPermissionRequestHandler(){},protocol:{handle(s,h){a.equal(s,'control-autonomo');handler=h}}};
class Window{constructor(options){a.equal(options.webPreferences.session,ses);a(options.webPreferences.sandbox);this.webContents={setWindowOpenHandler(){},on(){},print(){}}}on(){}async loadURL(url){try{const response=await handler({url});a.equal(response.status,200);a.match(response.headers.get('Content-Type'),/^text\/html/);const html=await response.text();const names=[...html.matchAll(/<script\b[^>]*data-desktop-script="([^"]+)"/g)].map(x=>x[1]);a(!/<script\b[^>]*\bsrc=/i.test(html));a(names.includes('store.js'));a(names.includes('desktop-adapter.js'));for(const name of names){const script=await handler({url:new URL(name,url).href});a.equal(script.status,200,name);a.match(script.headers.get('Content-Type'),/^text\/javascript/,name);const content=await script.text();a.equal(content,fs.readFileSync(path.join(__dirname,'../assets',name),'utf8'),name);new vm.Script(content,{filename:name})}for(const url of ['control-autonomo://evil/assets/store.js','control-autonomo://app/assets/a%5cb','control-autonomo://app/assets/%2e%2e%2fsecret'])a((await handler({url})).status>=400);console.log('OK Protocolo Windows: HTML y '+names.length+' scripts completos, tipos correctos y rutas protegidas');load.resolve()}catch(e){load.reject(e)}}}
const electron={app,BrowserWindow:Window,ipcMain:{handle(){}},dialog:{showErrorBox(_t,msg){load.reject(Error(msg))}},shell:{},session:{fromPartition:()=>ses},protocol:{registerSchemesAsPrivileged(s){a(!ready);a.equal(s[0].scheme,'control-autonomo');a.deepEqual(JSON.parse(JSON.stringify(s[0].privileges)),{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true});registered=true}},Menu:{setApplicationMenu(){},buildFromTemplate:x=>x}};
try{const filename=path.resolve(__dirname,'../main.cjs');vm.runInNewContext(fs.readFileSync(filename,'utf8'),{require:n=>n==='electron'?electron:n==='./policy.cjs'?require('../policy.cjs'):require(n),__dirname:path.dirname(filename),process:{env:{CA_DESKTOP_TEST:'1',CA_TEST_PROFILE:base}},Response,console});await done}finally{fs.rmSync(base,{recursive:true,force:true})}
})().catch(e=>{console.error(e);process.exitCode=1});
