(function(root){'use strict';
const statuses=['pending','confirmed','completed','cancelled'],active=a=>['pending','confirmed'].includes(a.status),minutes=s=>/^([01]\d|2[0-3]):[0-5]\d$/.test(s)?Number(s.slice(0,2))*60+Number(s.slice(3)):NaN;
function ensure(d){const t=CATPV.ensure(d);return t.appointments??=[]}
function validate(d){const appointments=ensure(d),ids=new Set(),t=CATPV.ensure(d);if(!Array.isArray(appointments))throw Error('Agenda no válida');for(const p of t.products)if(p.duration!=null&&(!Number.isInteger(p.duration)||p.duration<1||p.duration>1440))throw Error('Duración de servicio no válida');for(const a of appointments){if(typeof a.id!=='string'||!/^[-A-Za-z0-9_]{1,100}$/.test(a.id)||ids.has(a.id)||!CATPV.validDate(a.date)||!Number.isFinite(minutes(a.time))||!Number.isInteger(a.duration)||a.duration<1||minutes(a.time)+a.duration>1440||!statuses.includes(a.status)||typeof a.notes!=='string'||a.notes.length>500||typeof a.customerName!=='string'||!Array.isArray(a.services)||a.services.some(s=>!t.products.some(p=>p.id===s.productId)||typeof s.name!=='string'||!Number.isInteger(s.duration)||s.duration<1)||(a.customerId&&!t.customers.some(c=>c.id===a.customerId))||(a.saleId&&!t.sales.some(s=>s.id===a.saleId&&s.appointmentId===a.id)))throw Error('Cita no válida');ids.add(a.id)}return d}
function save(d,input){const t=CATPV.ensure(d),list=ensure(d),old=list.find(a=>a.id===input.id);if(old?.saleId)throw Error('La cita ya tiene una venta; consúltala en TPV.');const customer=input.customerId?t.customers.find(c=>c.id===input.customerId&&!c.archived):null;if(input.customerId&&!customer)throw Error('Selecciona un cliente activo.');const services=input.productIds.map(id=>{const p=t.products.find(p=>p.id===id&&p.kind==='service'&&!p.archived);if(!p?.duration)throw Error('Configura la duración del servicio en Catálogo.');return {productId:p.id,name:p.name,duration:p.duration}});if(!Array.isArray(input.productIds)||new Set(input.productIds).size!==input.productIds.length)throw Error('Revisa los servicios de la cita.');const a={id:old?.id||crypto.randomUUID(),customerId:input.customerId||'',customerName:customer?.name||'Cliente ocasional',date:input.date,time:input.time,duration:Number(input.duration),services,notes:input.notes.trim(),status:input.status};const candidate=structuredClone(d);ensure(candidate);candidate.tpv.appointments=list.filter(x=>x.id!==a.id).concat(a);validate(candidate);const conflicts=list.filter(x=>x.id!==a.id&&active(x)&&active(a)&&x.date===a.date&&minutes(x.time)<minutes(a.time)+a.duration&&minutes(a.time)<minutes(x.time)+x.duration);if(old)Object.assign(old,a);else list.push(a);return {appointment:a,conflicts}}
function end(a){const n=minutes(a.time)+a.duration;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function addCustomer(d,{name,phone='',email=''}){name=String(name).trim();phone=String(phone).trim();email=String(email).trim();if(!name||name.length>120||phone.length>60||email.length>160)throw Error('Revisa los datos del cliente.');const customer={id:crypto.randomUUID(),name,phone,email,notes:'',archived:false};CATPV.ensure(d).customers.push(customer);return customer}
function contactLinks(phone){const raw=String(phone??'').trim();if(!raw||!/^[+\d\s().-]+$/.test(raw)||raw.slice(1).includes('+'))return null;let digits=raw.replace(/\D/g,''),international=raw.startsWith('+')||raw.startsWith('00');if(raw.startsWith('00'))digits=digits.slice(2);if(digits.length<7||digits.length>15||(international&&digits.startsWith('0')))return null;return {call:'tel:'+(international?'+':'')+digits,whatsapp:international?'https://wa.me/'+digits:digits.length===9?'https://wa.me/34'+digits:null}}
function remove(d,id){const list=ensure(d),a=list.find(a=>a.id===id);if(!a)throw Error('La cita ya no existe.');for(const sale of CATPV.ensure(d).sales)if(sale.appointmentId===id)delete sale.appointmentId;CATPV.ensure(d).appointments=list.filter(a=>a.id!==id)}
root.CAAgenda={ensure,validate,save,remove,end,minutes,addCustomer,contactLinks};
})(globalThis);
